### class Task

In [2]:
import numpy as np

In [3]:
s =np.genfromtxt(r"C:\Users\LENOVO\Downloads\Iris_clean_-_Copy.csv",dtype = 'float64',delimiter = ",")

In [4]:
s

array([[      nan,       nan,       nan,       nan],
       [5.100e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.700e+00, 3.200e+00, 1.300e+00, 2.000e-01],
       [4.600e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.400e+00,       nan, 1.700e+00, 4.000e-01],
       [4.600e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.400e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.100e+00,       nan, 1.000e-01],
       [5.400e+00, 3.700e+00, 1.500e+00, 2.000e-01],
       [4.800e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.800e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.300e+00, 3.000e+00, 1.100e+00, 1.000e-01],
       [5.800e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.700e+00, 4.400e+00, 1.500e+00, 4.000e-01],
       [5.040e+01,       nan, 1.300e+00, 4.000e-01],
       [5.100e+00, 3.500e+00, 1.400e+00, 3.000

In [5]:
sapl = s[1:,0]
sapl

array([  5.1,   4.9,   4.7,   4.6,  50. ,   5.4,   4.6,   5. ,   4.4,
         4.9,   5.4,   4.8,   4.8,   4.3,   5.8,   5.7,  50.4,   5.1,
         5.7,   5.1,   5.4,   5.1,   4.6,   5.1,   4.8,   5. ,   5. ,
         5.2,   5.2,   4.7,   4.8,   5.4,   5.2,   5.5,   4.9,   5. ,
         5.5,   4.9,   4.4,   5.1,   5. ,   4.5,   4.4,   5. ,   5.1,
         4.8,   5.1,   4.6,   5.3,   5. ,   7. ,   6.4,   6.9,   5.5,
         6.5,   5.7, 116.3,   4.9,   6.6,   5.2,   5. ,   5.9,   6. ,
         6.1,   5.6,   6.7,   5.6,   5.8,   6.2,   5.6,   5.9,   6.1,
         6.3,   6.1,   6.4,   6.6,   6.8,   6.7,   6. ,   5.7,   5.5,
         5.5,   5.8,   6. ,   5.4,   6. ,   6.7,   6.3,   5.6,   5.5,
         5.5,   6.1,   5.8,   5. ,   5.6,   5.7,   5.7,   6.2,   5.1,
         5.7,   6.3,   5.8,   7.1,   6.3,   6.5,   7.6,   4.9,   7.3,
         6.7,   7.2,   6.5,   6.4,   6.8,   5.7,   5.8,   6.4,   6.5,
         7.7,   7.7,   6. ,   6.9,   5.6,   7.7,   6.3,   6.7,   7.2,
         6.2,   6.1,

In [6]:
sapl = np.where(sapl == -1,np.nan,sapl)
sapl

array([  5.1,   4.9,   4.7,   4.6,  50. ,   5.4,   4.6,   5. ,   4.4,
         4.9,   5.4,   4.8,   4.8,   4.3,   5.8,   5.7,  50.4,   5.1,
         5.7,   5.1,   5.4,   5.1,   4.6,   5.1,   4.8,   5. ,   5. ,
         5.2,   5.2,   4.7,   4.8,   5.4,   5.2,   5.5,   4.9,   5. ,
         5.5,   4.9,   4.4,   5.1,   5. ,   4.5,   4.4,   5. ,   5.1,
         4.8,   5.1,   4.6,   5.3,   5. ,   7. ,   6.4,   6.9,   5.5,
         6.5,   5.7, 116.3,   4.9,   6.6,   5.2,   5. ,   5.9,   6. ,
         6.1,   5.6,   6.7,   5.6,   5.8,   6.2,   5.6,   5.9,   6.1,
         6.3,   6.1,   6.4,   6.6,   6.8,   6.7,   6. ,   5.7,   5.5,
         5.5,   5.8,   6. ,   5.4,   6. ,   6.7,   6.3,   5.6,   5.5,
         5.5,   6.1,   5.8,   5. ,   5.6,   5.7,   5.7,   6.2,   5.1,
         5.7,   6.3,   5.8,   7.1,   6.3,   6.5,   7.6,   4.9,   7.3,
         6.7,   7.2,   6.5,   6.4,   6.8,   5.7,   5.8,   6.4,   6.5,
         7.7,   7.7,   6. ,   6.9,   5.6,   7.7,   6.3,   6.7,   7.2,
         6.2,   6.1,

In [7]:
np.nanmean(sapl)

7.510559006211181

In [9]:
sapl1 = np.where(np.isnan(sapl),np.nanmean(sapl),sapl).astype('float32')
sapl1

array([  5.1     ,   4.9     ,   4.7     ,   4.6     ,  50.      ,
         5.4     ,   4.6     ,   5.      ,   4.4     ,   4.9     ,
         5.4     ,   4.8     ,   4.8     ,   4.3     ,   5.8     ,
         5.7     ,  50.4     ,   5.1     ,   5.7     ,   5.1     ,
         5.4     ,   5.1     ,   4.6     ,   5.1     ,   4.8     ,
         5.      ,   5.      ,   5.2     ,   5.2     ,   4.7     ,
         4.8     ,   5.4     ,   5.2     ,   5.5     ,   4.9     ,
         5.      ,   5.5     ,   4.9     ,   4.4     ,   5.1     ,
         5.      ,   4.5     ,   4.4     ,   5.      ,   5.1     ,
         4.8     ,   5.1     ,   4.6     ,   5.3     ,   5.      ,
         7.      ,   6.4     ,   6.9     ,   5.5     ,   6.5     ,
         5.7     , 116.3     ,   4.9     ,   6.6     ,   5.2     ,
         5.      ,   5.9     ,   6.      ,   6.1     ,   5.6     ,
         6.7     ,   5.6     ,   5.8     ,   6.2     ,   5.6     ,
         5.9     ,   6.1     ,   6.3     ,   6.1     ,   6.4  

In [10]:
cond = (sapl > 8) | (sapl < 3)

In [11]:
np.sum(cond)

4

In [12]:
sepal_length = np.where(cond,7,sapl1)
sepal_length

array([5.1     , 4.9     , 4.7     , 4.6     , 7.      , 5.4     ,
       4.6     , 5.      , 4.4     , 4.9     , 5.4     , 4.8     ,
       4.8     , 4.3     , 5.8     , 5.7     , 7.      , 5.1     ,
       5.7     , 5.1     , 5.4     , 5.1     , 4.6     , 5.1     ,
       4.8     , 5.      , 5.      , 5.2     , 5.2     , 4.7     ,
       4.8     , 5.4     , 5.2     , 5.5     , 4.9     , 5.      ,
       5.5     , 4.9     , 4.4     , 5.1     , 5.      , 4.5     ,
       4.4     , 5.      , 5.1     , 4.8     , 5.1     , 4.6     ,
       5.3     , 5.      , 7.      , 6.4     , 6.9     , 5.5     ,
       6.5     , 5.7     , 7.      , 4.9     , 6.6     , 5.2     ,
       5.      , 5.9     , 6.      , 6.1     , 5.6     , 6.7     ,
       5.6     , 5.8     , 6.2     , 5.6     , 5.9     , 6.1     ,
       6.3     , 6.1     , 6.4     , 6.6     , 6.8     , 6.7     ,
       6.      , 5.7     , 5.5     , 5.5     , 5.8     , 6.      ,
       5.4     , 6.      , 6.7     , 6.3     , 5.6     , 5.5  

In [13]:
np.mean(sepal_length)

5.9414682

In [14]:
np.median(sepal_length)

5.9

In [15]:
Range= np.max(sepal_length) - np.min(sepal_length)
Range

3.3999996

In [16]:
np.var(sepal_length)

0.74443555

In [17]:
np.std(sepal_length)

0.8628068

#### sort the sepal width in ascending order.

In [18]:
width = s[1:,1]
np.sort(width)

array([  2. ,   2.2,   2.2,   2.2,   2.3,   2.3,   2.3,   2.3,   2.4,
         2.4,   2.4,   2.5,   2.5,   2.5,   2.5,   2.5,   2.5,   2.5,
         2.5,   2.5,   2.5,   2.6,   2.6,   2.6,   2.6,   2.7,   2.7,
         2.7,   2.7,   2.7,   2.7,   2.7,   2.7,   2.7,   2.7,   2.7,
         2.7,   2.8,   2.8,   2.8,   2.8,   2.8,   2.8,   2.8,   2.8,
         2.8,   2.8,   2.8,   2.8,   2.8,   2.8,   2.8,   2.8,   2.8,
         2.9,   2.9,   2.9,   2.9,   2.9,   2.9,   2.9,   2.9,   2.9,
         2.9,   2.9,   3. ,   3. ,   3. ,   3. ,   3. ,   3. ,   3. ,
         3. ,   3. ,   3. ,   3. ,   3. ,   3. ,   3. ,   3. ,   3. ,
         3. ,   3. ,   3. ,   3. ,   3. ,   3. ,   3. ,   3. ,   3. ,
         3.1,   3.1,   3.1,   3.1,   3.1,   3.1,   3.1,   3.1,   3.1,
         3.1,   3.2,   3.2,   3.2,   3.2,   3.2,   3.2,   3.2,   3.2,
         3.2,   3.2,   3.2,   3.2,   3.2,   3.2,   3.2,   3.3,   3.3,
         3.3,   3.3,   3.3,   3.3,   3.3,   3.4,   3.4,   3.4,   3.4,
         3.4,   3.4,

In [19]:
width = np.where(width == -1,np.nan,width)
width


array([  3.5,   3. ,   3.2,   3.1,   3.6,   nan,   3.4,   3.4,   2.9,
         3.1,   3.7,   3.4, 130. ,   3. ,   4. ,   4.4,   nan,   3.5,
         3.8,   3.8,   3.4,   3.7,   3.6,   3.3,   3.4,   3. ,  34. ,
         3.5,   3.4,   3.2,   3.1,   3.4,   4.1,   4.2,   3.1,   3.2,
         3.5,   3.1,   3. ,   3.4,   3.5,   2.3,   3.2,   3.5,   3.8,
         3. ,   3.8,   3.2,   3.7,   3.3,   3.2,   3.2,   nan,   2.3,
         2.8,   2.8,   3.3,   2.4,   2.9,   2.7,   2. ,   3. ,   2.2,
         2.9,   2.9,   3.1,   3. ,   2.7,   2.2,   2.5,   3.2,   2.8,
         2.5,   nan,   2.9,   3. ,   2.8,   3. ,   2.9,   2.6,   2.4,
         2.4,   2.7,   2.7,   3. ,   3.4,   3.1,   2.3,   3. ,   2.5,
         2.6,   3. , 112.6,   2.3,   2.7,   3. ,   2.9,   2.9,   2.5,
         2.8,   3.3,   2.7,   3. ,   2.9,   3. ,   3. ,   2.5,   2.9,
         2.5,   3.6,   3.2,   2.7,   3. ,   2.5,   2.8,   3.2,   3. ,
         3.8,   2.6,   2.2,   3.2,   2.8,   2.8,   2.7,   3.3,   3.2,
         2.8,   3. ,

In [20]:
np.nanmean(width)

4.713207547169812

In [23]:
width1 = np.where(np.isnan(width),np.nanmean(width),width).astype('float')
width1

array([  3.5       ,   3.        ,   3.2       ,   3.1       ,
         3.6       ,   4.71320755,   3.4       ,   3.4       ,
         2.9       ,   3.1       ,   3.7       ,   3.4       ,
       130.        ,   3.        ,   4.        ,   4.4       ,
         4.71320755,   3.5       ,   3.8       ,   3.8       ,
         3.4       ,   3.7       ,   3.6       ,   3.3       ,
         3.4       ,   3.        ,  34.        ,   3.5       ,
         3.4       ,   3.2       ,   3.1       ,   3.4       ,
         4.1       ,   4.2       ,   3.1       ,   3.2       ,
         3.5       ,   3.1       ,   3.        ,   3.4       ,
         3.5       ,   2.3       ,   3.2       ,   3.5       ,
         3.8       ,   3.        ,   3.8       ,   3.2       ,
         3.7       ,   3.3       ,   3.2       ,   3.2       ,
         4.71320755,   2.3       ,   2.8       ,   2.8       ,
         3.3       ,   2.4       ,   2.9       ,   2.7       ,
         2.        ,   3.        ,   2.2       ,   2.9 

In [24]:
condi = (width> 5 )| (width <2)

In [25]:
condi

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [26]:
np.sum(condi)   #outlier

3

In [27]:
sepal_width = np.where(condi,4,width1)
sepal_width

array([3.5       , 3.        , 3.2       , 3.1       , 3.6       ,
       4.71320755, 3.4       , 3.4       , 2.9       , 3.1       ,
       3.7       , 3.4       , 4.        , 3.        , 4.        ,
       4.4       , 4.71320755, 3.5       , 3.8       , 3.8       ,
       3.4       , 3.7       , 3.6       , 3.3       , 3.4       ,
       3.        , 4.        , 3.5       , 3.4       , 3.2       ,
       3.1       , 3.4       , 4.1       , 4.2       , 3.1       ,
       3.2       , 3.5       , 3.1       , 3.        , 3.4       ,
       3.5       , 2.3       , 3.2       , 3.5       , 3.8       ,
       3.        , 3.8       , 3.2       , 3.7       , 3.3       ,
       3.2       , 3.2       , 4.71320755, 2.3       , 2.8       ,
       2.8       , 3.3       , 2.4       , 2.9       , 2.7       ,
       2.        , 3.        , 2.2       , 2.9       , 2.9       ,
       3.1       , 3.        , 2.7       , 2.2       , 2.5       ,
       3.2       , 2.8       , 2.5       , 4.71320755, 2.9    

In [28]:
np.mean(width1)

4.713207547169811

In [29]:
np.median(width1)

3.0

In [30]:
Range = np.max(sepal_width) - np.min(sepal_width)
Range

2.7132075471698123

In [31]:
np.var(sepal_width)

0.2821182805759136

In [32]:
np.std(sepal_width)

0.5311480778237964

###### 5.after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values

In [33]:
np.savetxt('cleaned_iris.txt',sepal_length)

In [34]:
np.loadtxt('cleaned_iris.txt')

array([5.0999999 , 4.9000001 , 4.69999981, 4.5999999 , 7.        ,
       5.4000001 , 4.5999999 , 5.        , 4.4000001 , 4.9000001 ,
       5.4000001 , 4.80000019, 4.80000019, 4.30000019, 5.80000019,
       5.69999981, 7.        , 5.0999999 , 5.69999981, 5.0999999 ,
       5.4000001 , 5.0999999 , 4.5999999 , 5.0999999 , 4.80000019,
       5.        , 5.        , 5.19999981, 5.19999981, 4.69999981,
       4.80000019, 5.4000001 , 5.19999981, 5.5       , 4.9000001 ,
       5.        , 5.5       , 4.9000001 , 4.4000001 , 5.0999999 ,
       5.        , 4.5       , 4.4000001 , 5.        , 5.0999999 ,
       4.80000019, 5.0999999 , 4.5999999 , 5.30000019, 5.        ,
       7.        , 6.4000001 , 6.9000001 , 5.5       , 6.5       ,
       5.69999981, 7.        , 4.9000001 , 6.5999999 , 5.19999981,
       5.        , 5.9000001 , 6.        , 6.0999999 , 5.5999999 ,
       6.69999981, 5.5999999 , 5.80000019, 6.19999981, 5.5999999 ,
       5.9000001 , 6.0999999 , 6.30000019, 6.0999999 , 6.40000

In [35]:
np.savetxt('cleaned_iris.txt',sepal_width)

In [36]:
np.loadtxt('cleaned_iris.txt')

array([3.5       , 3.        , 3.2       , 3.1       , 3.6       ,
       4.71320755, 3.4       , 3.4       , 2.9       , 3.1       ,
       3.7       , 3.4       , 4.        , 3.        , 4.        ,
       4.4       , 4.71320755, 3.5       , 3.8       , 3.8       ,
       3.4       , 3.7       , 3.6       , 3.3       , 3.4       ,
       3.        , 4.        , 3.5       , 3.4       , 3.2       ,
       3.1       , 3.4       , 4.1       , 4.2       , 3.1       ,
       3.2       , 3.5       , 3.1       , 3.        , 3.4       ,
       3.5       , 2.3       , 3.2       , 3.5       , 3.8       ,
       3.        , 3.8       , 3.2       , 3.7       , 3.3       ,
       3.2       , 3.2       , 4.71320755, 2.3       , 2.8       ,
       2.8       , 3.3       , 2.4       , 2.9       , 2.7       ,
       2.        , 3.        , 2.2       , 2.9       , 2.9       ,
       3.1       , 3.        , 2.7       , 2.2       , 2.5       ,
       3.2       , 2.8       , 2.5       , 4.71320755, 2.9    