### class Task

In [53]:
import numpy as np

In [3]:
s =np.genfromtxt(r"C:\Users\LENOVO\Downloads\Iris_clean_-_Copy.csv",dtype = 'int32',delimiter = ",")

In [4]:
s

array([[ -1,  -1,  -1,  -1],
       [  5,   3,   1,   0],
       [  4,   3,   1,   0],
       [  4,   3,   1,   0],
       [  4,   3,   1,  10],
       [ 50,   3,   1,   0],
       [  5,  -1,   1,   0],
       [  4,   3,   1,   0],
       [  5,   3,   1,   0],
       [  4,   2,   1,   0],
       [  4,   3,  -1,   0],
       [  5,   3,   1,   0],
       [  4,   3,   1,   0],
       [  4, 130,   1,  10],
       [  4,   3,   1,   0],
       [  5,   4,   1,   0],
       [  5,   4,   1,   0],
       [ 50,  -1,   1,   0],
       [  5,   3,   1,   0],
       [  5,   3,   1,   0],
       [  5,   3,   1,   0],
       [  5,   3,   1,   0],
       [  5,   3,   1,   0],
       [  4,   3,   1,   0],
       [  5,   3,   1,   0],
       [  4,   3,   1,   0],
       [  5,   3,   1,   0],
       [  5,  34,   1,   0],
       [  5,   3,   1,   0],
       [  5,   3,   1, 110],
       [  4,   3,   1,   0],
       [  4,   3,   1,   0],
       [  5,   3,   1,   0],
       [  5,   4,   1,   0],
       [  5,  

In [5]:
sapl = s[1:,0]
sapl

array([  5,   4,   4,   4,  50,   5,   4,   5,   4,   4,   5,   4,   4,
         4,   5,   5,  50,   5,   5,   5,   5,   5,   4,   5,   4,   5,
         5,   5,   5,   4,   4,   5,   5,   5,   4,   5,   5,   4,   4,
         5,   5,   4,   4,   5,   5,   4,   5,   4,   5,   5,   7,   6,
         6,   5,   6,   5, 116,   4,   6,   5,   5,   5,   6,   6,   5,
         6,   5,   5,   6,   5,   5,   6,   6,   6,   6,   6,   6,   6,
         6,   5,   5,   5,   5,   6,   5,   6,   6,   6,   5,   5,   5,
         6,   5,   5,   5,   5,   5,   6,   5,   5,   6,   5,   7,   6,
         6,   7,   4,   7,   6,   7,   6,   6,   6,   5,   5,   6,   6,
         7,   7,   6,   6,   5,   7,   6,   6,   7,   6,   6,   6,  70,
        -1,  -1,   6,   6,   6,   7,   6,   6,   6,   6,   6,   6,   5,
         6,   6,   6,   6,   6,   6,   5,   5,   7,  -1,  -1,   7,   4,
         7,   6,   5,   5,   7,   6,   7,   6,   6])

In [6]:
sapl = np.where(sapl == -1,np.nan,sapl)
sapl

array([  5.,   4.,   4.,   4.,  50.,   5.,   4.,   5.,   4.,   4.,   5.,
         4.,   4.,   4.,   5.,   5.,  50.,   5.,   5.,   5.,   5.,   5.,
         4.,   5.,   4.,   5.,   5.,   5.,   5.,   4.,   4.,   5.,   5.,
         5.,   4.,   5.,   5.,   4.,   4.,   5.,   5.,   4.,   4.,   5.,
         5.,   4.,   5.,   4.,   5.,   5.,   7.,   6.,   6.,   5.,   6.,
         5., 116.,   4.,   6.,   5.,   5.,   5.,   6.,   6.,   5.,   6.,
         5.,   5.,   6.,   5.,   5.,   6.,   6.,   6.,   6.,   6.,   6.,
         6.,   6.,   5.,   5.,   5.,   5.,   6.,   5.,   6.,   6.,   6.,
         5.,   5.,   5.,   6.,   5.,   5.,   5.,   5.,   5.,   6.,   5.,
         5.,   6.,   5.,   7.,   6.,   6.,   7.,   4.,   7.,   6.,   7.,
         6.,   6.,   6.,   5.,   5.,   6.,   6.,   7.,   7.,   6.,   6.,
         5.,   7.,   6.,   6.,   7.,   6.,   6.,   6.,  70.,  nan,  nan,
         6.,   6.,   6.,   7.,   6.,   6.,   6.,   6.,   6.,   6.,   5.,
         6.,   6.,   6.,   6.,   6.,   6.,   5.,   

In [7]:
np.nanmean(sapl)

7.049689440993789

In [8]:
sapl1 = np.where(np.isnan(sapl),np.nanmean(sapl),sapl).astype('int32')
sapl1

array([  5,   4,   4,   4,  50,   5,   4,   5,   4,   4,   5,   4,   4,
         4,   5,   5,  50,   5,   5,   5,   5,   5,   4,   5,   4,   5,
         5,   5,   5,   4,   4,   5,   5,   5,   4,   5,   5,   4,   4,
         5,   5,   4,   4,   5,   5,   4,   5,   4,   5,   5,   7,   6,
         6,   5,   6,   5, 116,   4,   6,   5,   5,   5,   6,   6,   5,
         6,   5,   5,   6,   5,   5,   6,   6,   6,   6,   6,   6,   6,
         6,   5,   5,   5,   5,   6,   5,   6,   6,   6,   5,   5,   5,
         6,   5,   5,   5,   5,   5,   6,   5,   5,   6,   5,   7,   6,
         6,   7,   4,   7,   6,   7,   6,   6,   6,   5,   5,   6,   6,
         7,   7,   6,   6,   5,   7,   6,   6,   7,   6,   6,   6,  70,
         7,   7,   6,   6,   6,   7,   6,   6,   6,   6,   6,   6,   5,
         6,   6,   6,   6,   6,   6,   5,   5,   7,   7,   7,   7,   4,
         7,   6,   5,   5,   7,   6,   7,   6,   6])

In [9]:
cond = (sapl > 8) | (sapl < 3)

In [10]:
np.sum(cond)

4

In [44]:
sepal_length = np.where(cond,7,sapl1)
sepal_length

array([5, 4, 4, 4, 7, 5, 4, 5, 4, 4, 5, 4, 4, 4, 5, 5, 7, 5, 5, 5, 5, 5,
       4, 5, 4, 5, 5, 5, 5, 4, 4, 5, 5, 5, 4, 5, 5, 4, 4, 5, 5, 4, 4, 5,
       5, 4, 5, 4, 5, 5, 7, 6, 6, 5, 6, 5, 7, 4, 6, 5, 5, 5, 6, 6, 5, 6,
       5, 5, 6, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 6, 5, 6, 6, 6,
       5, 5, 5, 6, 5, 5, 5, 5, 5, 6, 5, 5, 6, 5, 7, 6, 6, 7, 4, 7, 6, 7,
       6, 6, 6, 5, 5, 6, 6, 7, 7, 6, 6, 5, 7, 6, 6, 7, 6, 6, 6, 7, 7, 7,
       6, 6, 6, 7, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 5, 7, 7, 7,
       7, 4, 7, 6, 5, 5, 7, 6, 7, 6, 6])

In [12]:
np.mean(sepal_length)

5.484848484848484

In [13]:
np.median(sepal_length)

5.0

In [15]:
Range= np.max(sepal_length) - np.min(sepal_length)
Range

3

In [16]:
np.var(sepal_length)

0.8073461891643708

In [18]:
np.std(sepal_length)

0.8985244510665087

#### sort the sepal width in ascending order.

In [54]:
width = s[1:,1]
np.sort(width)

array([ -1,  -1,  -1,  -1,  -1,  -1,   2,   2,   2,   2,   2,   2,   2,
         2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
         2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
         2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
         2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
         2,   2,   2,   2,   2,   2,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   4,   4,   4,   4,  34, 112, 130])

In [55]:
width = np.where(width == -1,np.nan,width)
width


array([  3.,   3.,   3.,   3.,   3.,  nan,   3.,   3.,   2.,   3.,   3.,
         3., 130.,   3.,   4.,   4.,  nan,   3.,   3.,   3.,   3.,   3.,
         3.,   3.,   3.,   3.,  34.,   3.,   3.,   3.,   3.,   3.,   4.,
         4.,   3.,   3.,   3.,   3.,   3.,   3.,   3.,   2.,   3.,   3.,
         3.,   3.,   3.,   3.,   3.,   3.,   3.,   3.,  nan,   2.,   2.,
         2.,   3.,   2.,   2.,   2.,   2.,   3.,   2.,   2.,   2.,   3.,
         3.,   2.,   2.,   2.,   3.,   2.,   2.,  nan,   2.,   3.,   2.,
         3.,   2.,   2.,   2.,   2.,   2.,   2.,   3.,   3.,   3.,   2.,
         3.,   2.,   2.,   3., 112.,   2.,   2.,   3.,   2.,   2.,   2.,
         2.,   3.,   2.,   3.,   2.,   3.,   3.,   2.,   2.,   2.,   3.,
         3.,   2.,   3.,   2.,   2.,   3.,   3.,   3.,   2.,   2.,   3.,
         2.,   2.,   2.,   3.,   3.,   2.,   3.,   2.,   3.,   2.,   3.,
         2.,   2.,   2.,   3.,   3.,  nan,   3.,   3.,   3.,   3.,   2.,
         3.,   3.,  nan,   2.,   3.,   3.,   3.,   

In [56]:
np.nanmean(width)

4.29559748427673

In [73]:
width1 = np.where(np.isnan(width),np.nanmean(width),width).astype('int32')
width1

array([  3,   3,   3,   3,   3,   4,   3,   3,   2,   3,   3,   3, 130,
         3,   4,   4,   4,   3,   3,   3,   3,   3,   3,   3,   3,   3,
        34,   3,   3,   3,   3,   3,   4,   4,   3,   3,   3,   3,   3,
         3,   3,   2,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         4,   2,   2,   2,   3,   2,   2,   2,   2,   3,   2,   2,   2,
         3,   3,   2,   2,   2,   3,   2,   2,   4,   2,   3,   2,   3,
         2,   2,   2,   2,   2,   2,   3,   3,   3,   2,   3,   2,   2,
         3, 112,   2,   2,   3,   2,   2,   2,   2,   3,   2,   3,   2,
         3,   3,   2,   2,   2,   3,   3,   2,   3,   2,   2,   3,   3,
         3,   2,   2,   3,   2,   2,   2,   3,   3,   2,   3,   2,   3,
         2,   3,   2,   2,   2,   3,   3,   4,   3,   3,   3,   3,   2,
         3,   3,   4,   2,   3,   3,   3,   2,   2,   2,   3,   3,   2,
         2,   2,   3,   2,   2,   2,   3,   3,   2])

In [58]:
condi = (width> 5 )| (width <2)

In [59]:
condi

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [60]:
np.sum(condi)   #outlier

3

In [61]:
sepal_width = np.where(condi,4,width1)
sepal_width

array([3, 3, 3, 3, 3, 4, 3, 3, 2, 3, 3, 3, 4, 3, 4, 4, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 4, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2, 2, 3,
       3, 2, 2, 2, 3, 2, 2, 4, 2, 3, 2, 3, 2, 2, 2, 2, 2, 2, 3, 3, 3, 2,
       3, 2, 2, 3, 4, 2, 2, 3, 2, 2, 2, 2, 3, 2, 3, 2, 3, 3, 2, 2, 2, 3,
       3, 2, 3, 2, 2, 3, 3, 3, 2, 2, 3, 2, 2, 2, 3, 3, 2, 3, 2, 3, 2, 3,
       2, 2, 2, 3, 3, 4, 3, 3, 3, 3, 2, 3, 3, 4, 2, 3, 3, 3, 2, 2, 2, 3,
       3, 2, 2, 2, 3, 2, 2, 2, 3, 3, 2])

In [62]:
np.mean(width1)

4.284848484848485

In [63]:
np.median(width1)

3.0

In [64]:
Range = np.max(sepal_width) - np.min(sepal_width)
Range

2

In [66]:
np.var(sepal_width)

0.37340679522497705

In [67]:
np.std(sepal_width)

0.6110702048250897

###### 5.after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values

In [68]:
np.savetxt('cleaned_iris.txt',sepal_length)

In [69]:
np.loadtxt('cleaned_iris.txt')

array([5., 4., 4., 4., 7., 5., 4., 5., 4., 4., 5., 4., 4., 4., 5., 5., 7.,
       5., 5., 5., 5., 5., 4., 5., 4., 5., 5., 5., 5., 4., 4., 5., 5., 5.,
       4., 5., 5., 4., 4., 5., 5., 4., 4., 5., 5., 4., 5., 4., 5., 5., 7.,
       6., 6., 5., 6., 5., 7., 4., 6., 5., 5., 5., 6., 6., 5., 6., 5., 5.,
       6., 5., 5., 6., 6., 6., 6., 6., 6., 6., 6., 5., 5., 5., 5., 6., 5.,
       6., 6., 6., 5., 5., 5., 6., 5., 5., 5., 5., 5., 6., 5., 5., 6., 5.,
       7., 6., 6., 7., 4., 7., 6., 7., 6., 6., 6., 5., 5., 6., 6., 7., 7.,
       6., 6., 5., 7., 6., 6., 7., 6., 6., 6., 7., 7., 7., 6., 6., 6., 7.,
       6., 6., 6., 6., 6., 6., 5., 6., 6., 6., 6., 6., 6., 5., 5., 7., 7.,
       7., 7., 4., 7., 6., 5., 5., 7., 6., 7., 6., 6.])

In [70]:
np.savetxt('cleaned_iris.txt',sepal_width)

In [71]:
np.loadtxt('cleaned_iris.txt')

array([3., 3., 3., 3., 3., 4., 3., 3., 2., 3., 3., 3., 4., 3., 4., 4., 4.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 4., 3., 3., 3., 3., 3., 4., 4.,
       3., 3., 3., 3., 3., 3., 3., 2., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 4., 2., 2., 2., 3., 2., 2., 2., 2., 3., 2., 2., 2., 3., 3., 2.,
       2., 2., 3., 2., 2., 4., 2., 3., 2., 3., 2., 2., 2., 2., 2., 2., 3.,
       3., 3., 2., 3., 2., 2., 3., 4., 2., 2., 3., 2., 2., 2., 2., 3., 2.,
       3., 2., 3., 3., 2., 2., 2., 3., 3., 2., 3., 2., 2., 3., 3., 3., 2.,
       2., 3., 2., 2., 2., 3., 3., 2., 3., 2., 3., 2., 3., 2., 2., 2., 3.,
       3., 4., 3., 3., 3., 3., 2., 3., 3., 4., 2., 3., 3., 3., 2., 2., 2.,
       3., 3., 2., 2., 2., 3., 2., 2., 2., 3., 3., 2.])