**Creation of ndarray**

1. Write python code to create 3d array in different ways with 15 elements.
2. Array Creation:
a. Create a 4D NumPy array containing the first 12 positive integers as arr1.
b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.
3. Find all attributes of array1 and array2
4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.


**Array Slicing and Indexing:**

a. Creating Arrays:
      - Create a 1-dimensional NumPy array  arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29].
      - Create a 2-dimensional NumPy array  arr2  with the values  [[0, 1, 2], [3, 4, 5], [6, 7, 8]].
      
 b.Basic Indexing:
      - Print the element at index 3 of  arr1.
      - Print the element at row 2, column 1 of  arr2

   c. Array Slicing:
      - Print the first five elements of `arr1`.
      - Print the subarray of `arr2` consisting of the last two rows and the first two columns.
       - Print every second element starting from index 1 up to index 7 of `arr1`.







**Data Type Manipulation**

a. Creating Arrays with Specific Data Types:
      - Create a 1-dimensional NumPy array `int_array` with the values `[1, 2, 3, 4, 5]` and the data type `int16`.
      - Create a 1-dimensional NumPy array `float_array` with the values `[0.1, 0.2, 0.3, 0.4, 0.5]` and the data type `float64`.
      
b. Data Type Conversion:
      - Convert the `float_array` to an array with data type `int32`. Print the result.
      - Convert the `int_array` to an array with data type `float32`. Print the result.

**Generating Random Numbers:**

1.	Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

2.	Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

3.	Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

4.	Apply descriptive statistics for rand_matrix.


**Analyze the Data:**

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]




Describe the data using numpy array.
Measure the following:
1.	How many employees are getting more less than 50000?

2.	Is it following Normal Distribution?

3.	What is the median salary?

4.	What is the range of salaries for this company?

5.	Find the salaries between average salary and 75% of salaries?

6.	How many employees are getting less than 25 % of salaries ?



### Creation of ndarray

**1.Write python code to create 3d array in different ways with 15 elements.**

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],ndmin = 3)   #using ndmin
arr1

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [3]:
arr1.reshape(5,3,1)   #by using reshape method

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [4]:
arr1 = np.array([[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]])     #using triple []
arr1

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

**2.Array Creation: a. Create a 4D NumPy array containing the first 12 positive integers as arr1. b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.**

In [5]:
arr = np.arange(1,13)
arr1 = np.array([[[arr]]])    #4D numpy array containing the first 12 positive int.
arr1

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]]])

In [6]:
#b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1.

In [7]:
np.random.rand(1,5,4)

array([[[0.56928767, 0.41476299, 0.1546742 , 0.74579317],
        [0.96786424, 0.66985549, 0.30092415, 0.039124  ],
        [0.02442685, 0.60636207, 0.58167819, 0.41858121],
        [0.5134802 , 0.60528127, 0.96681756, 0.95784977],
        [0.83090815, 0.41508476, 0.71725795, 0.4675036 ]]])

**3.Find all attributes of array1 and array2**

In [8]:
arr1

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]]])

In [9]:
arr1.dtype

dtype('int32')

In [10]:
arr1.size

12

In [11]:
arr1.nbytes

48

In [12]:
arr1.itemsize

4

**4.Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.**

In [13]:
np.mean(arr1)

6.5

In [14]:
np.median(arr1)

6.5

In [15]:
np.var(arr1)

11.916666666666666

In [16]:
np.std(arr1)

3.452052529534663

In [50]:
Q1 = np.percentile(arr1,25)
Q1

8.75

In [54]:
Q3 = np.percentile(arr1,75)
Q3

48.75

In [52]:
Q1 = np.percentile(arr1,25)
Q3 = np.percentile(arr1,75)
IQR = Q3 - Q1
IQR

40.0

In [55]:
lower_limit = Q1 - (1.5 * IQR)
lower_limit

-51.25

In [56]:
upper_limit = Q3 + (1.5 * IQR)
upper_limit

108.75

### Array Slicing and Indexing:

In [18]:
arr1 = np.array([0,11,26,73,42,51,6,77,8,29])
arr1

array([ 0, 11, 26, 73, 42, 51,  6, 77,  8, 29])

In [19]:
arr2 = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**b.Basic Indexing: - Print the element at index 3 of arr1.  
Print the element at row 2, column 1 of arr2**

In [20]:
arr1[3]

73

In [21]:
arr2[2,1]

7

In [22]:
arr1[0:5]

array([ 0, 11, 26, 73, 42])

In [23]:
arr3 = arr2[1:3 , 0:2]
arr3

array([[3, 4],
       [6, 7]])

In [24]:
arr1[1:8:2]

array([11, 73, 51, 77])

### Data Type Manipulation

**a. Creating Arrays with Specific Data Types: - Create a 1-dimensional NumPy array int_array with the values [1, 2, 3, 4, 5] and the data type int16. - Create a 1-dimensional NumPy array float_array with the values [0.1, 0.2, 0.3, 0.4, 0.5] and the data type float64.**

In [25]:
arr = np.array([1,2,3,4,5],'int16')
arr

array([1, 2, 3, 4, 5], dtype=int16)

In [26]:
arr3 = np.array([0.1,0.2,0.3,0.4,0.5])
arr3.dtype

dtype('float64')

In [27]:
arr3

array([0.1, 0.2, 0.3, 0.4, 0.5])

**b. Data Type Conversion: - Convert the float_array to an array with data type int32. Print the result. - Convert the int_array to an array with data type float32. Print the result.**

In [28]:
arr4 = np.array(arr3,dtype = 'int32')
arr4

array([0, 0, 0, 0, 0])

In [29]:
np.array([arr],dtype = 'float32')

array([[1., 2., 3., 4., 5.]], dtype=float32)

### Generating Random Numbers:

**Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).**


In [30]:
rand_integers = np.random.randint(0,100,10)
rand_integers

array([38, 64, 37, 45, 33, 54, 35, 84, 25, 84])

**Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.**


In [31]:
rand_uniform = np.random.uniform(-1,1,5)
rand_uniform

array([-0.2072848 , -0.96876551, -0.01113779, -0.9479373 ,  0.67182227])

**Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix**


In [32]:
rand_matrix = np.random.randint(50,100,16).reshape(4,4)
rand_matrix

array([[69, 79, 87, 62],
       [93, 93, 89, 51],
       [82, 54, 51, 79],
       [85, 80, 79, 79]])

In [33]:
rand_matrix.ndim

2

### Analyze the Data:

Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

Describe the data using numpy array. Measure the following: 
1. How many employees are getting more and less than 50000?

2.Is it following Normal Distribution?
3.What is the median salary?
4.What is the range of salaries for this company?
5.Find the salaries between average salary and 75% of salaries?
6.How many employees are getting less than 25 % of salaries ?

In [34]:
Salaries = np.array([87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638])

In [35]:
Salaries

array([  87877,   54494,   54804,   85051,   52453,   31250,   94868,
         66349,   39828,   60501,   58570,   74906,   41671,   51428,
         56414,   98446,   56819,   82833,   50477,   62898,   99658,
         89224,   34225,   79172,   32199,   63795,   90947,   55723,
         64557, 3113638])

In [36]:
len(Salaries[Salaries > 50000])   #how many employes getting more than 50000

25

In [37]:
m = Salaries[Salaries < 50000]     #how many employes getting less than 50000
len(m)

5

In [38]:
average_salaries  = np.mean(Salaries)     # mean of salaries
average_salaries

166169.16666666666

In [39]:
s =np.median(Salaries)      #median of salaries
s  

61699.5

In [40]:
Range = np.max(Salaries) - np.min(Salaries)   # Range of salaries of this company  
Range

3082388

In [41]:
Q1 = np.percentile(Salaries,25)
Q1

52963.25

In [42]:
Q3 = np.percentile(Salaries,75)
Q3

84496.5

In [43]:
IQR = Q3 - Q1
IQR

31533.25

In [44]:
lower = Q1 - (1.5 *IQR)
upper = Q3 + (1.5 * IQR)

In [45]:
lower

5663.375

In [46]:
upper

131796.375

In [47]:
Salaries[(Salaries < average_salaries) &  (Salaries > Q3)]

array([87877, 85051, 94868, 98446, 99658, 89224, 90947])

**2.Is it following Normal Distribution?**

No, its not normally distributed.

In [48]:
Salaries[Salaries<lower]

array([], dtype=int32)

In [49]:
Salaries[upper < Salaries] 

array([3113638])