#### 1.Whrite python code to create array in different ways.

In [15]:
import numpy as np

In [3]:
arr = np.array([10,20,30,40,50])    #using array
arr

array([10, 20, 30, 40, 50])

In [27]:
list1 = [1,2,3,4,5]    # from list
np.array(list1)

array([1, 2, 3, 4, 5])

In [5]:
tuple1 = (1,2,3,4,5)   #from tuple

In [6]:
np.array(tuple1)

array([1, 2, 3, 4, 5])

In [7]:
np.zeros(6)       #from zeros

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(5)     #form ones

array([1., 1., 1., 1., 1.])

In [11]:
np.arange(1,11)   #

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Array creation:

##### a.create a 1D NumPy array containing the first 12 positive integers as arr1.

In [28]:
arr1 = np.arange(1,13)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

##### b. create a 1D NumPy array1 with 20 elements containing integers between 0 and 12 using linspace.

In [26]:
arr2 = np.linspace(1,12,20)
arr2

array([ 1.        ,  1.57894737,  2.15789474,  2.73684211,  3.31578947,
        3.89473684,  4.47368421,  5.05263158,  5.63157895,  6.21052632,
        6.78947368,  7.36842105,  7.94736842,  8.52631579,  9.10526316,
        9.68421053, 10.26315789, 10.84210526, 11.42105263, 12.        ])

#### Find all attributes of array1 and array2

In [29]:
arr1.dtype

dtype('int32')

In [30]:
arr1.size

12

In [31]:
arr1.nbytes

48

In [32]:
arr1.itemsize

4

In [25]:
#arr2

In [33]:
arr2.dtype

dtype('float64')

In [34]:
arr2.size

20

In [35]:
arr2.nbytes

160

##### Apply measure and describe the data(attributes and descriptive statistics) to above arrays using NumPy.

In [36]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
np.mean(arr1)

6.5

In [38]:
np.median(arr1)

6.5

In [40]:
Range = max(arr1)- min(arr1)
Range

11

In [41]:
np.var(arr1)

11.916666666666666

In [42]:
np.std(arr1)

3.452052529534663

In [47]:
Q1 = np.percentile(arr1,25)
Q3 = np.percentile(arr1,75)
IQR = Q3 - Q1
IQR

5.5