### Data Cleaning using numpy

**The following are the student marks of a class**
[44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]



1. Find the no of outliers and missing values?
2. replace the outliers with 45 and missing value with 87.
3. what is the average marks of students after 2nd step?
4. How many students got less than 60 marks?
5. what is the maximum marks?
6. Convert the marks to float32.

### Solving Linear Equations


    
1. 2x + 3y - z = 10

    x - y + 2z = 5
    
    3x + 2y + z = 12
    
    
    
2. 2x + y - z + 3w = 8

    3x - 2y + 2z + 2w = 1
    
    x + 3y - 2z + w = 7
    
    4x - y + z - 2w = 3
   
   
   
3. 4x + 2y - 3z = 10

    -2x + 3y + z = -3
    
    x - y + 2z = 4
    
Solve the system of equations using NumPy's linalg.solve function.


### Conditional Selection with np.where()


1.	Generate a random 1D array A of 10 integers between 1 and 100.

2.	Use np.where() to find the indices where the elements of A are greater than 50.

3.	Create a new array B that contains elements from A where the condition is met.

4.	Calculate the mean of array B and print it along with arrays A and B.

### Replace Values with np.where()

1.	Create a 4x4 random integer matrix C with values between -10 and 10.

2.	Use np.where() to replace all negative values in matrix C with 0.

3.	Print the original matrix C and the modified matrix.

### Data Cleaning using numpy

[44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53, 44]

**Find the no of outliers and missing values?**

In [98]:
import numpy as np

In [99]:
marks = np.array([44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53, 44])

In [100]:
marks

array([ 44.,  24.,  nan,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  nan,  nan,   3.,  56.,  81.,  59., 122.,  92.,  nan,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.])

In [101]:
np.isnan(marks)


array([False, False,  True, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False])

In [107]:
np.sum(np.isnan(marks))  # missing values

4

In [ ]:
# replace missing values by 87

In [102]:
mark1 = np.where(np.isnan(marks),87,marks).astype('int16')
mark1

array([ 44,  24,  87,  59,  32,  96, 188,  52,  62,  58,  52, 120,  87,
        87,   3,  56,  81,  59, 122,  92,  87,  87,  96,  97,   1,  19,
         2,  53,  44], dtype=int16)

In [104]:
cond = (marks > 100 ) | (marks < 0)   #outlier
cond

array([False, False, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False])

In [105]:
np.sum(cond)

3

In [ ]:
#replace outliers by 45

In [109]:
S = np.where(cond,45,mark)
S

array([44, 24, 87, 59, 32, 96, 45, 52, 62, 58, 52, 45, 87, 87,  3, 56, 81,
       59, 45, 92, 87, 87, 96, 97,  1, 19,  2, 53, 44], dtype=int16)

In [ ]:
#what is the average marks of students after 2nd step?

In [110]:
np.mean(S)

56.96551724137931

In [ ]:
#How many students got less than 60 marks?

In [111]:
len(S[S<60])

18

In [ ]:
#what is the maximum marks?

In [114]:
np.max(S)

97

### Solving Linear Equations

2x + 3y - z = 10

x - y + 2z = 5

3x + 2y + z = 12

In [6]:
a = np.array([[2,3,-1],[1,-1,2],[3,2,1]])
a

array([[ 2,  3, -1],
       [ 1, -1,  2],
       [ 3,  2,  1]])

In [7]:
b = np.array([10,5,12])
b

array([10,  5, 12])

In [8]:
np.linalg.solve(a,b)

array([-6.75539944e+15,  6.75539944e+15,  6.75539944e+15])

In [11]:
a1 = np.array([[2,1,-1,3],[3,-2,2,2],[1,3,-2,1],[4,-1,1,-2]])
a1

array([[ 2,  1, -1,  3],
       [ 3, -2,  2,  2],
       [ 1,  3, -2,  1],
       [ 4, -1,  1, -2]])

In [14]:
b1 = np.array([8,1,7,3])
b1

array([8, 1, 7, 3])

In [15]:
np.linalg.solve(a1,b1)

array([ 1.73170732, -0.75609756, -3.46341463,  0.6097561 ])

In [17]:
a2 = np.array([[4,2,-3],[-2,3,1],[1,-1,2]])
a2

array([[ 4,  2, -3],
       [-2,  3,  1],
       [ 1, -1,  2]])

In [18]:
b2 = np.array([10,-3,4])
b2

array([10, -3,  4])

In [20]:
np.linalg.solve(a2,b2)

array([2.85365854, 0.6097561 , 0.87804878])

### Conditional Selection with np.where() 

In [ ]:
# Generate a random 1D array A of 10 integers between 1 and 100.

In [73]:
A = np.random.randint(1,100,10)
A

array([25, 55, 30, 11,  5, 12, 76, 61, 66, 95])

**Use np.where() to find the indices where the elements of A are greater than 50.**

In [74]:
c = np.array(A[A >50])
c

array([55, 76, 61, 66, 95])

In [75]:
#Use np.where() to find the indices where the elements of A are greater than 50.

In [78]:
a1 = np.where(A>50)
a1

(array([1, 6, 7, 8, 9], dtype=int64),)

In [ ]:
#Create a new array B that contains elements from A where the condition is met.

In [83]:
B = np.array(A[A>50]) 
B

array([55, 76, 61, 66, 95])

In [ ]:
#Calculate the mean of array B and print it along with arrays A and B.

In [89]:
np.mean(B)    #mean of B

70.6
[25 55 30 11  5 12 76 61 66 95]
[55 76 61 66 95]


### Replace Values with np.where()¶

In [ ]:
# Create a 4x4 random integer matrix C with values between -10 and 10.

In [93]:
C = np.random.randint(-10,10,16).reshape(4,4)
C

array([[  6,   8,  -3,  -5],
       [ -7,  -1,  -2,  -6],
       [ -4,   6,   1, -10],
       [ -7,   0,  -7,   2]])

In [ ]:
#Use np.where() to replace all negative values in matrix C with 0.

In [94]:
D = np.where(C < 0 , 0,C)
D

array([[6, 8, 0, 0],
       [0, 0, 0, 0],
       [0, 6, 1, 0],
       [0, 0, 0, 2]])

In [ ]:
#Print the original matrix C and the modified matrix.

In [97]:
print(C)
print(D)

[[  6   8  -3  -5]
 [ -7  -1  -2  -6]
 [ -4   6   1 -10]
 [ -7   0  -7   2]]
[[6 8 0 0]
 [0 0 0 0]
 [0 6 1 0]
 [0 0 0 2]]
